### ISSUE TITLE
Add AmiiSwap

### ISSUE THREAD

**Issue by flying-sheep** [noahc3/SDSetup#100]
Depends on emuiibo, so deselecting emuiibo should deselect Amiiswap and selecting AmiiSwap should also select emuiibo.

https://github.com/FuryBaguette/AmiiSwap

**Comment by noahc3** [comment]
It was already there, I updated it.

I don't think AmiiSwap should be dependent that way... there are lots of people who go to SDSetup after getting a pack like Kosmos just for homebrew.
