### ISSUE TITLE
Backed up files to mac. Now can't delete the file from SD Card as its a MacBinary file

### ISSUE THREAD

**Issue by oceanderp** [noahc3/SDSetup#102]
It refuses to be deleted.

**Comment by StevenMattera** [comment]
Can you give steps to how you did this. I have a Mac so I can see if I can reproduce it.

**Comment by oceanderp** [comment]
of course. So my mac is an 2014 running yosemite. 

I was following SDSetup and what I originally did was put 'SD' folder onto the SD, not knowing that the files inside were going onto the root of the SD. I only realise this in hindsight, but maybe has something to do with it?

Anyway, so I'm going through the precautions, access RCM, and backup eMMC BOOT0/1. This went fine,  I moved it off and out from the SD, then deleted the 'backup' folder as instructed. Then I backed up Backup eMMC RAW GPP. I take the SD out of the switch and put it into my mac and find I can't move or delete the file. It says it can't be moved to the trash because it can't be deleted.

This has also somehow locked it all, because I can't even move the files out of 'SD' to the root of the folder anyway.

**Comment by oceanderp** [comment]
seems like  rawnand.bin cant delete

**Comment by oceanderp** [comment]
Also, even on DiskUtility I can't erase anything. Its like its made it completely lock down

**Comment by StevenMattera** [comment]
I don't have my Mac or Switch with me at the moment, but have you tried fixing the archive bit in Hekate? (I think it's under Tools.)

**Comment by oceanderp** [comment]
I finally found solution to this issue, but now when I push payload hekate it turns on and goes through  its bootup with its logos etc and then nothing? Just doesn't continue to  power the switch on...
