### ISSUE TITLE
Update SdSetup

### ISSUE THREAD

**Issue by Sblerky** [noahc3/SDSetup#103]
Hello, can you update SdSetup with AMS 0.9.1 please ?
Thank you

**Comment by noahc3** [comment]
Waiting for Hekate and Kosmos

**Comment by Xirious** [comment]
Is it safe to update the AMS after the .zip download from SDSetup?

**Comment by noahc3** [comment]
Temporarily updated with a chainload to fusee-primary & Atmos 0.9.1.
