### ISSUE TITLE
Support Atmosphere 0.92 (6f85b11)

### ISSUE THREAD

**Issue by gRoberts84** [noahc3/SDSetup#107]
Hi there,

I have a iPatched 4.1.0 device, which unfortunately suffers from a bug that Atmosphere has patched but when attempting to manually integrate the patch/update with the SDSetup, it loads straight into CFW AMS 0.92.

Is it possible to retain Hekate so I can setup EmuMMC and continue from there?

**Comment by noahc3** [comment]
I've updated Kosmos with the latest shadowpatched Atmosphere and a fixed Hekate which should work on 4.1 now. Can you try redownloading?

**Comment by gRoberts84** [comment]
Thank you @noahc3 - I will try that when I get home from work.
