### ISSUE TITLE
Biskeygen not working

### ISSUE THREAD

**Issue by lung9** [noahc3/SDSetup#108]
When i upload the files and try to press "Derive BIS Keys" nothing happens.

**Comment by shchmue** [comment]
oh yeah the fuse file format changed

**Comment by lung9** [comment]
where do i get the new required files

**Comment by shchmue** [comment]
this tool will need an update. in the meantime just get your bis keys with biskeydump or lockpick_rcm

**Comment by lung9** [comment]
will do.

**Comment by Ultracoolguy** [comment]
Using the SBK and the TSEC key doesn't work either. This is using biskeydump.

**Comment by Hammaz19** [comment]
SBK and TSEC dont work, neither do the fuse files.
Is it possible to use the keys retrieved from biskeydump?
e.g
bis_key_00 = ****
bis_key_01 = ****
bis_key_02 = ****
bis_key_03 = **** 

if so, where do I input them? I only see the Crypto (Upper) and Tweak (Lower) boxes.

if thats not possible, is this tool being updated?

**Comment by games12366** [comment]
Hello have the same problem as you and you still have not updated the site to have his BIS keys and when I dump my keys via the payload biskey dump I have three lines HWI SBK TSEC his do not go help for hacdiskmount I hope you will soon update the site thank you

**Comment by noahc3** [comment]
Biskeygen on SDSetup has been fixed and the guide has been corrected.
