### ISSUE TITLE
Add nxdumptool.

### ISSUE THREAD

**Issue by DarkMatterCore** [noahc3/SDSetup#114]
Available [here](https://github.com/DarkMatterCore/nxdumptool).

Not only offers XCI/NSP dumping. ExeFS/RomFS browsing/dumping capabilities are bundled in as well, which are very helpful for datamining procedures and the creation of LayeredFS/SaltyNX mods.

Works under all available CFWs. Needs the console to be at least on 4.0.0.

**Comment by noahc3** [comment]
Done.
