### ISSUE TITLE
SDSetup not loading ...

### ISSUE THREAD

**Issue by aeropic** [noahc3/SDSetup#115]
Hi,
First of all thanks for your job!
I tried loading the SDsetup page but the web page seems stalled on a "loading..." screen, and this forever.
Any help welcome.
Thanks

**Comment by noahc3** [comment]
Works for me so I need some more info:

* Browser and Version
* OS and Version
* Any enabled anti-viruses or anti-malware

**Comment by aeropic** [comment]
Thanks fpr your answer Noahc3, the configuration was : 
- latest firefox
- windows XP
- anti viruses disabled (orange firewall)

Meanwhile, I uses another more recent PC (windows 10) and it worked like a charm.

**Comment by noahc3** [comment]
Firefox on XP is the ESR release, which does not support webassembly, and thus will not work with SDSetup. Nothing I can do about it.
