### ISSUE TITLE
The site is down

### ISSUE THREAD

**Issue by GusVonDamne** [noahc3/SDSetup#118]
It ain't there

**Comment by noahc3** [comment]
Yes, there was a notice it would be down.

**Comment by noahc3** [comment]
While we wait forever for GitHub to create the new SSL certificate, you can use http://sdsetup.com/ without encryption. You will probably need to clear site settings or use incognito/private browsing to bypass HSTS until the certificate is generated.

**Comment by noahc3** [comment]
It's back.
