### ISSUE TITLE
Pixel-Painter Update

### ISSUE THREAD

**Issue by 16BitWonder** [noahc3/SDSetup#12]
Hi there, love this project you've gotten set up!

I wanted to point out that I just updated Pixel-Painter to v1.6.0 and was hoping you would reflect that in your re-hosted homebrew projects.

Until recently I wasn't aware that it wasn't working as intended (basically broken) and had to be fixed, which is what v1.6.0 has done.

**Comment by noahc3** [comment]
Done!

**Comment by 16BitWonder** [comment]
I've just pushed what should be the final update to Pixel-Painter (v1.7.0).
Unless it breaks again and needs fixing, this should be the final update.

If/when you get the time, would you mind re-hosting the latest version?

**Comment by noahc3** [comment]
Sorry for the delay! Discord didn't ping me for whatever reason. Pixel-Painter is now updated to 1.7.0.
