### ISSUE TITLE
Atmosphere packages are out of date

### ISSUE THREAD

**Issue by raphapy** [noahc3/SDSetup#122]
New version was released
https://github.com/Atmosphere-NX/Atmosphere/releases/tag/0.9.4

**Comment by noahc3** [comment]
Waiting for Scires to stop pushing silent fixes.

**Comment by destinqo** [comment]
any updates? my son asking me, every day, about updates ;)

**Comment by BlingSniper1337** [comment]
@noahc3 few days passed since atmosphere got updated. What are you waiting for? Go update it

**Comment by jakibaki** [comment]
> few days passed since atmosphere got updated. Too lazy to upload fixes or what? Go update it.

Noah doesn't owe you anything, the update happens when it happens...

**Comment by noahc3** [comment]
I'll be pushing out autoupdates and the frontend overhaul tonight.

**Comment by noahc3** [comment]
Done.
