### ISSUE TITLE
sdsetup.com doesn't load in Safari

### ISSUE THREAD

**Issue by johnsonwalker** [noahc3/SDSetup#126]
Endless loading screen when accessing sdsetup.com in Safari on MacOS. Works fine in Firefox. I assume it's something to do with the DRep problem, but I don't think there's anything to disable in the settings to make it work.

**Comment by noahc3** [comment]
Safari's webassembly has problems. Last I checked it worked on the latest technogy preview Safari but that might have changed. Nothing I can do to fix it.

I'll probably remove the drep notice, hasn't been an issue for a year.
