### ISSUE TITLE
do not load on macOS Mojave

### ISSUE THREAD

**Issue by AlpGoXd** [noahc3/SDSetup#127]
do not load on macOS Mojave

**Comment by Jean-Daniel** [comment]
More specifically with Safari 13. It worked well on Mojave before Safari update.

**Comment by bktiger86** [comment]
Can also confirmed does not work on Mojave Safari 13.0.1

**Comment by noahc3** [comment]
Getting an OSX VM setup right now to see if this is fixed in Blazor yet.

**Comment by noahc3** [comment]
Verified fixed in 3.1, will have an update pushed today.
