### ISSUE TITLE
Feature request: List of component versions to be included to the output zip file

### ISSUE THREAD

**Issue by jakaja** [noahc3/SDSetup#131]
Home page shows nicely version numbers of each component.
When I download the zip file, that info is not included.

It would be nice to have a list of component versions inside the zip to be able to check later what versions have been downloaded (like a month ago).

component_versions.txt
- Atmosphere (Kosmos) (v0.9.4/v14.2)
- Homebrew App Store (v2.1)
- Homebrew Menu v3.1.1
...

---
*#134 merged:*

After download has started, there is a question:
Want to redownload in the future?
Save the following URL somewhere to immediately have the same packages pre-selected in the future:

It would be very convenient to have this URL inside the zip file being downloaded.
That way user only needs to save a (previous) zip file to update it at anytime.

**Comment by noahc3** [comment]
Sure I can do this. It will also probably useful whenever I decide to rewrite the homebrew app.

Is having it in the SD folder sufficient? (ex. sdsetup-x.x.x.zip/sd/sdsetup-versions.txt)

I'll also merge #134 into this issue and put the URL in a comment at the top.

**Comment by jakaja** [comment]
I think it should be at root of the zip as there are some components (with version numbers) at these folders as well:
sdsetup-x.x.x.zip/pc/
sdsetup-x.x.x.zip/payloads/

**Comment by noahc3** [comment]
Tracking in #203
