### ISSUE TITLE
nxdumptool located at incorrect folder

### ISSUE THREAD

**Issue by jakaja** [noahc3/SDSetup#132]
nxdumptool is at the output zip file at folder
sd\switch\**gcdumptool**\nxdumptool.nro

It must be at sd\switch\**nxdumptool**\nxdumptool.nro
as nxdumptool itself expects to be there -> NSWreleases.xml is searched for there only!

See the attached image.
![2019100615261200-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/24541264/66269199-7b958380-e84e-11e9-9d9d-58d78044de11.jpg)

**Comment by noahc3** [comment]
Fixed.
