### ISSUE TITLE
Feature request: Add a 'copy-to-clipboard' button next to the setup-URL

### ISSUE THREAD

**Issue by jakaja** [noahc3/SDSetup#133]
After download has started, there is a question:
Want to redownload in the future?
Save the following URL somewhere to immediately have the same packages pre-selected in the future: 

There should be a button next to the question which copies the URL to the clipboard. 
Current way is very old-fashioned, clumsy and user-unfriendly.

**Comment by thezoggy** [comment]
might be good to mimic how jqueryui.com does their custom download builder (bitwise the options) so it makes it easy to unpack and migrate if needed

**Comment by noahc3** [comment]
Done.
