### ISSUE TITLE
downloading the homebrew zip

### ISSUE THREAD

**Issue by 0fox0-hub** [noahc3/SDSetup#138]
everytime i download it, it loads for a little bit and then it gets stuck and stops downloading even though it says that it'll download in 30 seconds. whats going on?

**Comment by noahc3** [comment]
Is this still happening?

**Comment by azoreseuropa** [comment]
And the files are outdated.

**Comment by Lynx924** [comment]
Oh I thought that's what the maintenance fixed yesterday.

**Comment by noahc3** [comment]
Files aren't outdated, there is no new Kosmos release yet.

**Comment by 0fox0-hub** [comment]
Yes it's still happening
