### ISSUE TITLE
sdsetup.com is down

### ISSUE THREAD

**Issue by niksa3** [noahc3/SDSetup#141]
apologies if this is just maintenance but i wanted to let you know

**Comment by hax4dazy** [comment]
![image](https://user-images.githubusercontent.com/16256978/70741314-45c3be00-1d1b-11ea-85ac-bddcdc8630fc.png)

**Comment by niksa3** [comment]
thanks, i didn't know about the discord server

**Comment by hax4dazy** [comment]
... it is on the website.

**Comment by niksa3** [comment]
sdsetup.com doesn't say anything about discord

**Comment by hax4dazy** [comment]
![image](https://user-images.githubusercontent.com/16256978/70781070-10a08580-1d86-11ea-9722-1846b2bec4d3.png)
you where wrong

**Comment by DanielC-08** [comment]
@hax4dazy but if it was down they wouldn’t see it

**Comment by hax4dazy** [comment]
True true. But if they've visited the website before they would have seen that there was a discord.

**Comment by DanielC-08** [comment]
True, but they could have been new to the site and never visited it before. @hax4dazy
