### ISSUE TITLE
Website Failed to load

### ISSUE THREAD

**Issue by fortepc** [noahc3/SDSetup#144]
I'm not sure what the problem is, but I followed the "Atmosphere setup" link from [this post on reddit](https://www.reddit.com/r/SwitchNSPs/comments/cxucxk/complete_switch_hackingpiracy_guide/) and the page never loaded. https://www.sdsetup.com/console?switch%23atmosphere;atmos_musthave;atmos_bootlogo;kosmos_updater;kosmos_toolkit;atmos_sigpatch;atmos_hid-mitm;ldn_mitm;atmos_emuiibo;atmos_sys-clk;atmos_sysnetcheat;atmos_sysftpd;hbmenu;appstorenx;edizon;zerotwoxci;tinfoil;goldleaf;nxshell;lockpick;nxthemesinstaller;hekate;fusee-primary;lockpick_rcm;biskeydump;goldtree; was the full link.The page told me to report it so here's a screenshot of the page failing to load, along with the dev-console 

![image](https://user-images.githubusercontent.com/26149601/71548480-d554a800-297c-11ea-8a6d-47846ade55d7.png)

**Comment by noahc3** [comment]
Bad URL, ask the OP of that post to fix it (the %23 in the URL should be a #)
