### ISSUE TITLE
biskeygen different output for lower case letters for TSEC and SBK keys.

### ISSUE THREAD

**Issue by Toby4213** [noahc3/SDSetup#146]
The title says pretty much all.
The prod.keys file from Lockpick_RCM hast lower case letters for the hex values but using lower case letters for the tsec and sbk keys instead of upper case results in a different output.
URL: [https://sdsetup.com/biskeygen](https://sdsetup.com/biskeygen)

**Comment by noahc3** [comment]
Will push a fix later today.
