### ISSUE TITLE
Homebrew SD setup doesn't work

### ISSUE THREAD

**Issue by Gimmy46** [noahc3/SDSetup#147]
Hi all,

I've tried to download from the link below, but the page doesn't load.
I've already disinstalled my antivirus Avast, but the page still doesn't working.

thank you for your feedback

https://sdsetup.com/console?switch#atmosphere;atmos_musthave;atmos_bootlogo;kosmos_toolkit;appstorenx;hbmenu;pplay;checkpoint;edizon;goldleaf;fusee-primary;hekate;tegrarcmgui;4nxci;goldtree;ns-usbloader;atmos_sigpatch

**Comment by DanielC-08** [comment]
Seems to be working.

**Comment by hax4dazy** [comment]
Yeah same here.

**Comment by Gimmy46** [comment]
Yes, I’ve changed browser, and it works

Liverani Gianmarco

Il giorno 19 gen 2020, alle ore 20:00, hax4dazy <notifications@github.com> ha scritto:

﻿

Yeah same here.

**Comment by noahc3** [comment]
Which browser wasnt working and what version?

**Comment by Gimmy46** [comment]
I’ve used a mac with the last version of safari,

Liverani Gianmarco

Il giorno 19 gen 2020, alle ore 20:08, noahc3 <notifications@github.com> ha scritto:

﻿

Which browser wasnt working and what version?

**Comment by hax4dazy** [comment]
I don't know about safari but it is recommended that you'd use chrome or either firefox

**Comment by noahc3** [comment]
Duplicate #127
