### ISSUE TITLE
moving homebrew packages into their own folders

### ISSUE THREAD

**Issue by plaidman** [noahc3/SDSetup#15]
NX-Shell and Checkpoint create files and folders in the same directory as their nro file. This clutters up the switch directory and in some cases even makes useless directories show up in the homebrew menu. If you put them in `/sd/switch/NX-Shell/NX-Shell.nro` and `/sd/switch/Checkpoint/Checkpoint.nro` respectively, then the HBMenu will only show one icon and hide any additional files/directories associated with those apps.

**Comment by noahc3** [comment]
I'll get this done tomorrow!

**Comment by noahc3** [comment]
Done.
