### ISSUE TITLE
Some descriptions that need updating

### ISSUE THREAD

**Issue by cathery** [noahc3/SDSetup#153]
- **KosmosToolbox** -  missing author: cathery
- **KosmosToolbox** -  no longer has hid-mitm configuration as stated in the description
- **KosmosUpdater** - author's name was changed to NicholeMattera and should be updated in the description
- **sys-ftpd-light** - missing author: jakibaki
- **ldn_mitm** - no longer a kip as stated in the description
- **ovlSysmodule** - incorrectly labeled version as v1.0.2 (current version is v1.1.0)
- **Tinfoil** - incorrectly links to XorTroll's Goldleaf instead of Adubbz's Tinfoil
- **Quark** - version 0.8 now requires Java 9 or higher and should be updated in the description

Note: At the bottom of the Atmosphere/Kosmos CFW box, it incorrectly calls Kosmos Toolbox "the Kosmos Toolkit"

Note: Projects by AtlasNX are attributed to individiuals, but projects by RetroNX Team get attributed as a team. Other projects get attributed as a team and individually. Maybe figure out some consistency?

**Comment by friedkeenan** [comment]
The Tinfoil on SDSetup uses a commit from after the Tinfoil repo was given to Xor (that repo was later renamed to Goldleaf and stuff), so it's technically correct

**Comment by noahc3** [comment]
All fixed. ovlSysmodule had the autoupdate hint misconfigured to Tesla Menu, so the files and version number was wrong.
