### ISSUE TITLE
Page doesn’t load on Chrome on iPhone

### ISSUE THREAD

**Issue by solderjs** [noahc3/SDSetup#154]
https://sdsetup.com

Spinner spins forever on Chrome on iPhone

**Comment by solderjs** [comment]
Still hasn’t loaded on iPhone on Safari either, after about a minute of waiting.

**Comment by TechGeekGamer** [comment]
Maybe check your internet connection, loads fine for me.

**Comment by solderjs** [comment]
I’m on Gigabit WiFi in Utah.

I noticed because my buddy over in Atlanta, GA told me it wouldn’t load for him.

I’m on the latest beta iOS. I believe he’s on the latest stable.

That said, it takes a good 20 seconds to load over gigabit ETHERNET on my quad-core iMac. There I assume it’s due to in-browser C#-to-JS transpiring?

**Comment by noahc3** [comment]
I'm suddenly getting 20 second load time over here as well, its usually 3 seconds max. Will look into it.

**Comment by noahc3** [comment]
Can you try loading on your iMac again?

Don't own an iPhone to test with right now but I will try to borrow a friends tomorrow to investigate.

**Comment by solderjs** [comment]
Takes about 20-30 seconds still.

**Comment by NicholeMattera** [comment]
Just tested this on my iPad Air 2 and it worked just fine.

**Comment by solderjs** [comment]
I just loaded the homepage again (iMac, Chrome) and this particular time it loaded in < 1s.

Then I hit refresh again and it took a few seconds.

As of this moment it seems to take just a few seconds every time.

Also finally loaded on my phone in about 10s, for the first time.

**Comment by noahc3** [comment]
Few seconds is expected on consecutive runs since it needs to pull data from the server and construct the web page. The first run will take longer because the mono runtime and assemblies need to be downloaded (and will be cached for later runs).

**Comment by noahc3** [comment]
I've tested on an iPhone XR today and load time is about 5 seconds in Safari. Anything longer than that might just be from Github.
