### ISSUE TITLE
[Feature Request] Add SysDVR

### ISSUE THREAD

**Issue by StarOz** [noahc3/SDSetup#155]
A sysmodule that can capture switch games directly on your PC via USB or network.
https://github.com/exelix11/SysDVR

**Comment by noahc3** [comment]
SysDVR has a lot of different versions and setups (two different versions of the sysmodule, two different versions of the PC client, necessary drivers for different platforms, etc), plus it requires extensive viewing of the readme to set up. I don't think it makes sense to put on SDSetup right now.
