### ISSUE TITLE
When selecting Tesla Overlay and ovl-sysmodules, sdsetup won't add toolbox.json for modules

### ISSUE THREAD

**Issue by evertonstz** [noahc3/SDSetup#159]
This results in sysmodules like sys-ftpd-light, emuiibu, etc, not showing up in ovl-sysmodules' Tesla overlay as default, even if the user selected them to be installed in sdsetup, these toolbox.json files currently come bundled with Kosmos and are located inside `SD:/atmosphere/contents/`, more info can be found [here](https://gbatemp.net/threads/ovl-sysmodules-a-tesla-overlay-to-toggle-sysmodules.557455/)

**Comment by noahc3** [comment]
Fixed.
