### ISSUE TITLE
Can you add back the support for ReiNX 3.0?

### ISSUE THREAD

**Issue by dbw-holic** [noahc3/SDSetup#164]
Hi there, thank you for your work and it's been really quite helpful when the website helps build my own package. Given the fact that the resurrection of ReiNX for HOS 9.x+, would you consider to add back the support for this CFW? 

Thanks, 
David

**Comment by noahc3** [comment]
Maybe, but there won't be any major changes like this until I finish rewriting the backend server.

**Comment by noahc3** [comment]
ReiNX is abandoned so this won't be happening.
