### ISSUE TITLE
Slow downloads 

### ISSUE THREAD

**Issue by Stimzy** [noahc3/SDSetup#165]
Whenever I try to use your website the downloads always take forever and only downloads at 50 KB/s

**Comment by noahc3** [comment]
Our host occasionally gets drops in speed. I'm getting 10MBps right now though.

**Comment by Stimzy** [comment]
Can you please delete this issue since you replied

**Comment by Stimzy** [comment]
and btw its still 50 kb/s

**Comment by noahc3** [comment]
I recommend you check your internet connection. It could also be a temporary peering issue to your ISP.

![](https://puu.sh/FKf8V/9a58e891d7.png)

**Comment by Stimzy** [comment]
i download anything else and i get 5 mb/s
