### ISSUE TITLE
Signature Patches 

### ISSUE THREAD

**Issue by Unzeen023** [noahc3/SDSetup#173]
When I download and install the signature patches some games work and others don't.

**Comment by hrvylein** [comment]
Repository of signature patches moved and it seems sdsetup is pulling the patches from the archived one.

**Comment by hax4dazy** [comment]
No the link to the repo is outdated. They are still including the newest patches from the other repo

**Comment by noahc3** [comment]
I updated the link, the patches are manually updated on SDSetup and were always up to date with the other repo.
