### ISSUE TITLE
Missing Signature Patches (exefs_patches)

### ISSUE THREAD

**Issue by krouwndouwn** [noahc3/SDSetup#176]
On older SDSetup verions we could choose to build with signature patches but this option has been removed somehow. I still need some correct signature patches for newer Nintendo Switch firmware upgrades for playing game updates. This is the only thing i could find:

https://github.com/ITotalJustice/patches/releases/

Can this be usefull to rebuild the signature patches back into the SDSetup website?

**Comment by noahc3** [comment]
Signature patches have been removed from SDSetup due to a DMCA claim from Nintendo. You can find them on GBATemp or our Discord server.
