### ISSUE TITLE
Atmosphere's Daybreak is missing

### ISSUE THREAD

**Issue by slackerbob** [noahc3/SDSetup#181]
Daybreak, the new firmware updater that's included with atmosphere isn't an available option, and isn't included when atmosphere is selected.

https://github.com/Atmosphere-NX/Atmosphere/releases (it's included in the normal download)

**Comment by AmirSG2** [comment]
Probably this is in purpose, I noticed and dragged the daybreak.nro from the official atmosphere to my sd and...  now I can't boot properly into my updated firmware after using daybreak.

**Comment by HookedBehemoth** [comment]
No you must have done something else wrong. Seek support on discord. https://discord.gg/a4VeH8Z

**Comment by AmirSG2** [comment]
> Probably this is in purpose, I noticed and dragged the daybreak.nro from the official atmosphere to my sd and... now I can't boot properly into my updated firmware after using daybreak.

> No you must have done something else wrong. Seek support on discord. https://discord.gg/a4VeH8Z

Indeed, Daybreak had nothing to do with my problem. It is now fixed and Daybreak worked just fine.

**Comment by noahc3** [comment]
Daybreak is included with Atmosphere for now. I plan to make it a separate option eventually.
