### ISSUE TITLE
Bootloader folder missing from SD folder

### ISSUE THREAD

**Issue by Someone777** [noahc3/SDSetup#184]
Hekate doesn't work because those files were missing.  Due to the entire folder being missing, hekate_ipl.ini is also missing and the guide doesn't cover how to make one.  So, the guide is pretty much useless for getting anything actually working.

**Comment by noahc3** [comment]
Bootloader folder is included. Make sure you're not unselecting Atmosphere.

**Comment by Someone777** [comment]
Yeah, I was de-selecting it, thinking that I was actually selecting it.

**Comment by noahc3** [comment]
I'll look into changing it into a checkbox to make it more clear

**Comment by Someone777** [comment]
Thank you, I appreciate it.
