### ISSUE TITLE
Update multiple outdated packages

### ISSUE THREAD

**Issue by Krouwndouwn** [noahc3/SDSetup#190]
Homebrew Menu 3.3.0 > Homebrew Menu 3.4.0 (https://github.com/switchbrew/nx-hbmenu/releases)
EdiZon-SE 3.7.21 > EdiZon-SE 3.7.23 (https://github.com/tomvita/EdiZon-SE/releases)
RetroArch 1.8.4 > RetroArch 1.9.0 (https://buildbot.libretro.com/stable/1.9.0/nintendo/switch/libnx/)
NS-USBloader 2.1 > NS-USBloader 5.0 (https://github.com/developersu/ns-usbloader/releases)
Rekado 3.3.4 > Rekado 4.1 (https://github.com/MenosGrante/Rekado/releases)

**Comment by noahc3** [comment]
* hbmenu, Edizon-SE automatically update themselves (sync with HB appstore).
* RetroArch, NS-USBloader, Rekado now updated.

Thanks!
