### ISSUE TITLE
In the SD folder there is only Switch and hbmenu.nro

### ISSUE THREAD

**Issue by FantasticoStudioDaniele** [noahc3/SDSetup#192]
For a few days, in the SD folder I have only found the Switch folder and the hbmenu.nro file.
The other folders are not there, such as atmosphere, sept...

**Comment by noahc3** [comment]
Are you sure you are selecting Atmosphere at the top of the page?

![image](https://user-images.githubusercontent.com/6082749/103579124-5c483480-4e9d-11eb-9dd6-5aed47f36cf5.png)

Could you send the generated share link (shown after download) and upload the zip file?

**Comment by FantasticoStudioDaniele** [comment]
Hi,

yes I'm sure.
It worked a week ago.

Recommended + Atmosphere.

Generated share link:
https://www.sdsetup.com/console?switch#ovl_sysmodules;appstorenx;hbmenu;edizon;goldleaf;nxdumptool;lockpick;hekate;lockpick_rcm;

Zip file:
https://www.dropbox.com/s/pkv8pgcsekxb0um/SDSetup%281_4_21%29%20%282%29.zip?dl=0

**Comment by noahc3** [comment]
To be clear, you press the "Recommended Defaults" button and then hit download? Clicking atmosphere after choosing that button will deselect atmosphere.

**Comment by FantasticoStudioDaniele** [comment]
You're right, I'm deselecting atmosphere. My fault!

Thanks for the help!

**Comment by noahc3** [comment]
I added a checkbox to hopefully make it more clear.
