### ISSUE TITLE
sys-clk overlay needs to be removed since it crashes Atmosphere 0.18.0

### ISSUE THREAD

**Issue by jacoghi** [noahc3/SDSetup#194]
The repository where SDSetup is queueing its files from, https://github.com/HeadpatServices/sys-clk-Overlay has long been archived and is no longer updated. It also crashes the new Atmosphere 0.18.0.

It's also redundant since https://github.com/retronx-team/sys-clk/ comes with a more updated overlay as part of its package. Users who only want to have the overlay without the manager nro application might simply delete the nro from the Switch folder.

**Comment by noahc3** [comment]
Meant to do this last time I did a package cleanup but forgot, thanks!

**Comment by jacoghi** [comment]
Thank you so much for your hard work, my man, the website is awesome.
