### ISSUE TITLE
Atmosphère  have released new version 0.19.1 

### ISSUE THREAD

**Issue by tanhui2333** [noahc3/SDSetup#200]

**Comment by noahc3** [comment]
Since the changes are minor I'm going to wait for sys-con to update before pushing another update.

**Comment by tanhui2333** [comment]
> Since the changes are minor I'm going to wait for sys-con to update before pushing another update.

**Comment by noahc3** [comment]
Sounds like there were extensive HID changes in 12.0.0 that might delay a sys-con update, so I pushed the Atmosphere update now.
