### ISSUE TITLE
Add ubuntu and android.

### ISSUE THREAD

**Issue by joey-lg** [noahc3/SDSetup#204]
I wonder why it hasnt already been listed.

**Comment by noahc3** [comment]
Add what for ubuntu and android? We already have payload launchers for these platforms listed.

**Comment by joey-lg** [comment]
like the files for the OSs

**Comment by noahc3** [comment]
Ah, I see.

I think since there are different images designed for different sizes of SD cards, and different versions of each OS, it would be better to just let users download them manually from official sources when they are following a guide to install the OS.

**Comment by joey-lg** [comment]
oh. ok
