### ISSUE TITLE
hi can somebody help me i am stuck

### ISSUE THREAD

**Issue by igorkaufman** [noahc3/SDSetup#206]
I was on reinx and fw 7.0.1 
wanted to give it a go so i installed hekate from Homebrew sd setup following instructions, everything went well and i updated fw to 12.0.2 with Daybreak. I also factory reset my switch.
Now when i want to install any nsp game with goldleaf it gives me this error

error: 2145-0001 (0x291)
Module : ETickets (145)
Description: Unknown or undocumented error (1)

i tried 10 times to do everything from start, tryed fat32 and exfat,tryed many games but i get the error again and again.

Please help

**Comment by noahc3** [comment]
We do not provide support for piracy.
