### ISSUE TITLE
Site not loading

### ISSUE THREAD

**Issue by StillJam** [noahc3/SDSetup#209]
Having an issue with the site loading.
![Screenshot_20210707-081539](https://user-images.githubusercontent.com/87061448/124716051-8dacc600-defb-11eb-8067-f8816c7715de.jpg)

**Comment by noahc3** [comment]
Thanks for letting me know, I am able to reproduce this on mobile Chrome specifically, I'll take a closer look tomorrow.

In the meantime, mobile Firefox and Samsung Internet as well as desktop browsers seem to work fine if you need to access SDSetup.

**Comment by noahc3** [comment]
Unfortunately it was some cryptic WASM error, and I accidentally wiped my cache and it started working again, so I can't investigate the bug further.

I've purged Cloudflare's cache which might help. @StillJam Could you check if the site loads for you now?

**Comment by StillJam** [comment]
Nope still not working with google chrome

**Comment by noahc3** [comment]
Okay I can reliably reproduce this now but it will take me some time to find the cause.

In the meantime using something other than Chrome mobile or using desktop is the only option, unfortunately.

**Comment by StillJam** [comment]
No problem pal

**Comment by noahc3** [comment]
I think I've fixed it, @StillJam or @mrdolphin31 can you test if the site loads for you now?
