### ISSUE TITLE
Update multiple outdated packages

### ISSUE THREAD

**Issue by Krouwndouwn** [noahc3/SDSetup#211]
Important Items (Pre-configured bundles):
- [x] Atmosphère 1.1.1 > Atmosphère 1.2.4 (https://github.com/Atmosphere-NX/Atmosphere/releases)
- [x] Hekate 5.6.2 > Hekate 5.6.5 (https://github.com/CTCaer/hekate/releases)
- [x] Homebrew Menu 3.4.0 > Homebrew Menu 3.5.0 (https://github.com/switchbrew/nx-hbmenu/releases)

General Items:
- [x] EdiZon-SE 3.8.20 > EdiZon-SE 3.8.24 (https://github.com/tomvita/EdiZon-SE/releases)
- [x] Rekado 4.1 > Rekado 4.2 (https://github.com/MenosGrante/Rekado/releases)
- [x] JKSV 05-17-2021 > JKSV 09-01-2021 (https://github.com/J-D-K/JKSV/releases)
- [x] Lockpick_RCM 1.9.3 > Lockpick_RCM 1.9.6 (https://github.com/shchmue/Lockpick_RCM/releases)
- [x] NS-USBloader 5.0 > NS-USBloader 5.2 (https://github.com/developersu/ns-usbloader/releases)

Other Items:
- [x] Checkpoint 3.7.4 > 3.7.5-ams-19-compat (https://github.com/SciresM/Checkpoint/releases)
(This fix for checkpoint will work on atmosphere 19 with newer switch firmwares like 12.1.0. The original source can be changes back to https://github.com/FlagBrew/Checkpoint/releases when there is a new official and working release.)

**Comment by TheCatHacker562** [comment]
this happened to me, i needed to upgrade everything

**Comment by horst789github** [comment]
+1

**Comment by noahc3** [comment]
Sorry guys, I was hoping to get the rewrite done and point people there for new packages, but school started up again so it'll be a while longer. I'll see if I can get these updated today or tomorrow.

**Comment by noahc3** [comment]
Going to wait until Atmosphere 1.1.0 is out of pre-release then I'll push the updates.

**Comment by noahc3** [comment]
From the list, the following were updated:

Atmosphère 0.19.5 > Atmosphère 1.1.1
Hekate 5.5.8 > Hekate 5.6.2
Rekado 4.1 > Rekado 4.2
Lockpick_RCM 1.9.3 > Lockpick_RCM 1.9.6
NS-USBloader 5.0 > NS-USBloader 5.2
Checkpoint 3.7.4 > 3.7.4-ams-19-compat (kept the 3.7.4 version number on SDSetup but it is the updated nro)

The others are updated through appstore, manually updating these myself causes a lot of issues, so unfortunately they will be outdated for a little while longer. I'll see if I can submit these updates to the appstore so everything syncs, otherwise they won't be updated until I finish the rewrite.

**Comment by akiikhurana** [comment]
Thanks a-lot bro 
Already been using your pack its so convenient to use 
I have some doubts to ask
On launch menu 
I have four things
Cfw(sysmmc)
Cfw(emummc)
Stock
Fusee(mostly used for installing games and app )
So my question do i have to delete anything on my sd card for new atmosphere pack (e.g Sept folder) or something 
Thanks

**Comment by noahc3** [comment]
@akiikhurana 

It's recommended to delete the following files/folders:
```
/atmosphere/fusee-secondary.bin
/bootloader/payloads/fusee-primary.bin
/sept/ (whole folder)
```

However it is not required, you will just have extra unused files on your SD card.

**Comment by JoshuaJeme** [comment]
Atmosphère is 1.2.4 now, but it seems to be unstable.

**Comment by noahc3** [comment]
Thank you @Krouwndouwn for maintaining this list for so long!
