### ISSUE TITLE
SDSetup is down (2021/08/04)

### ISSUE THREAD

**Issue by Cham-Br9** [noahc3/SDSetup#213]
Just as the title says. Website is down and im wondering when it will come back up

**Comment by noahc3** [comment]
Yep was just about to pin an issue.

SDSetup is currently down due to an unknown issue on our server hosts end. PegaScape DNS and the guide are still functional.

Will update when I have more information.

**Comment by Cham-Br9** [comment]
Alright! Thanks for letting me know. So I should just take a break, grab a
coffee and just hangout until then? Or is there an alternative I can do
other than wait.

**Comment by noahc3** [comment]
Here's a package from about two weeks ago that contains the recommended defaults. There haven't been any major updates to anything since then.

[SDSetup7.20.21.zip](https://cdn.discordapp.com/attachments/483757068453543937/872633627769442304/SDSetup7.20.21.zip)

**Comment by Cham-Br9** [comment]
awesome thanks! Since I wont have the option to choose which specific emulators to get through the sight. Does the guide go over how to download them manually?

**Comment by noahc3** [comment]
I recommend going into the Homebrew Appstore and checking the Emulators category once you have everything installed to download them. The appstore is included in the bundle and will be accessible through the homebrew menu.

**Comment by noahc3** [comment]
Everything should be back online.
