### ISSUE TITLE
Site won't load

### ISSUE THREAD

**Issue by LSSJBroly** [noahc3/SDSetup#216]
i've been trying to get on the site for 15 minutes. it just won't load and it's stuck on the loading screen

**Comment by noahc3** [comment]
Are you on desktop? Try holding shift and pressing the refresh button.

**Comment by LSSJBroly** [comment]
i tried what you said and it still won't load

**Comment by noahc3** [comment]
Could you try again now?

**Comment by LSSJBroly** [comment]
works now, thank you so much!

**Comment by LSSJBroly** [comment]
really sorry, but when i try to select a pre-configured bundle nothing happens

**Comment by noahc3** [comment]
Yeah sorry I just broke all the buttons again, give me a minute

**Comment by LSSJBroly** [comment]
it's alright, sorry if i'm causing an issue for you!

**Comment by noahc3** [comment]
Could you refresh and try again?

**Comment by LSSJBroly** [comment]
still nothing. sorry

**Comment by LSSJBroly** [comment]
works now! thanks so much

**Comment by LSSJBroly** [comment]
and again, sorry if i bothered you at all

**Comment by noahc3** [comment]
I'm gonna keep this open cause I think it is going to break again.

And no worries, Google and Microsoft are really coming in clutch to screw me right now haha.

**Comment by LSSJBroly** [comment]
i actually only needed to download the recommended pre-configured bundle and i got it. so is it okay if i close the issue?
