### ISSUE TITLE
hecate giving error for fusee secondary missing when it shouldnt be in use.

### ISSUE THREAD

**Issue by keesoudwater34** [noahc3/SDSetup#220]
just redownloaded from the site with the hecate. but in the other stuff now package3 takes over for fusee but it still tries to read it. read up on it here [https://www.reddit.com/r/SwitchPirates/comments/pua0ec/keep_getting_this_error_while_trying_to_boot_cfw/](url)     . changed it and now it wants to boot. it still complains about sig's or signature files but i can force it past that with the ui.

im not sure what to think but figured id imform if it was suposed to be changed but never has been changed.

**Comment by noahc3** [comment]
Please make sure you are downloading from the main site www.sdsetup.com, the preview site currently has outdated packages. I've added a warning to the preview site to differentiate the two.
