### ISSUE TITLE
sysMMC Errors

### ISSUE THREAD

**Issue by LawlieMan** [noahc3/SDSetup#234]

**Comment by noahc3** [comment]
What error are you facing? Putting files in the ini folder is optional since the main configs are entered in hekate_ipl.ini.

**Comment by LawlieMan** [comment]
> What error are you facing? Putting files in the ini folder is optional since the main configs are entered in hekate_ipl.ini.

Sorry, I thought it was because of the ini folder, I don't know why but this error keeps appearing. (Image Link Here) https://drive.google.com/file/d/1-kXABOVYLv7dELYXmq5nBsBxN9OKbB46/view?usp=sharing

**Comment by noahc3** [comment]
SDSetup doesn't have latest Atmosphere to support 15.0.0 yet, I'll get those updated tonight.

**Comment by noahc3** [comment]
Hekate on SDSetup does not support FW 15.0 yet, I'll get that updated tonight. That said I don't think Atmosphere has updated for 15.0 yet, so you'll be stuck to using a lower version emuMMC.

**Comment by noahc3** [comment]
Packages updated
