### ISSUE TITLE
The page has been stuck loading for hours and I haven't found a fix :( I just want to mod my switch:(

### ISSUE THREAD

**Issue by WavyTurnip7834** [noahc3/SDSetup#242]
Idk why but the page has been stuck loading for HOURS and I can't really seem to find out the problem , if this is not solvable or you just don't know the answer just tell me how to install all the files manually like atmosphere (idk if it's included I'm just tryna mod my switch and the tutorial said to use your website) and other stuff so I can finish moddding my switch thank you ☺️ :)

**Comment by noahc3** [comment]
https://github.com/noahc3/SDSetup/issues/241#issuecomment-1399175614
