### ISSUE TITLE
Error message when trying to boot sysMMC

### ISSUE THREAD

**Issue by LawlieMan** [noahc3/SDSetup#243]
It give error  ):      
![WIN_20230226_17_14_29_Pro](https://user-images.githubusercontent.com/100043085/221437784-4c59735f-0801-4d83-8207-915a129b64c4.jpg)

**Comment by bielsoler98** [comment]
Did you know how to solve it?

**Comment by kurainooni** [comment]
this means, you Updated to firmware 16.0.0 on your Switch, which is not yet supported by the provided version of Hekate and Athmosphere, which means you will have to update them yourself, before you can boot again.

**Comment by noahc3** [comment]
Atmosphere/Hekate/etc is now updated on SDSetup. I usually avoid pushing Atmosphere pre-releases to SDSetup, but it's been about a week so I figure its probably *mostly* fine.

Download another zip from SDSetup and you should be good to go.
