### ISSUE TITLE
Failed to load resource: the server responded with a status of 403 (Forbidden)

### ISSUE THREAD

**Issue by phonzeh** [noahc3/SDSetup#25]
I receive this error in Chrome console whenever I try to build a package.
The status screen shows 0/XX files fetched.

Even selecting minimal will throw the error and report the following address unreachable.
https://s3.wasabisys.com/sdsetup/atmos_musthave/v10.1/sd/modules/required/exosphere.bin

Following the link, the XML page displays a message regarding improper use of a trial account.

**Comment by noahc3** [comment]
Fixed.
