### ISSUE TITLE
Toolbox keeps crashing

### ISSUE THREAD

**Issue by snifer1981** [noahc3/SDSetup#28]
1. I downloaded Atmosphere (selected all from General, no Sys modules). Deleted everything from SD card before copying files, except Nintendo folder.
2. Sdfiles Toolbox (Sdfiles Toolkit, CFW Settings) always crashes. I've tried using Hekate and fusee-primary, same result.
3. Everything else is working OK, btw.

What am I doing wrong?

**Comment by snifer1981** [comment]
> 
> 
> Looks like I broke something on my end. For now you can select the "SDFiles Defaults" package to have it work, or use the official SDFiles release.

I found out you didn't brake it. Toolbox needs at least 1 ini file in /bootloader/ini directory. I tried using an empty file and it works, too.

**Comment by noahc3** [comment]
Thanks for figuring that out. I've let WerWolv know about the bug.
