### ISSUE TITLE
Download doesn't start

### ISSUE THREAD

**Issue by crayt90** [noahc3/SDSetup#29]
Hi,

no matter what pre-configured bundles I select, after I hit "Download your ZIP" I see a black screen with a loading wheel and "0/397"
then the screen gets lit again with
"Operation Completed Your ZIP file should download within the next few seconds!"
but nothing happens after that.

I've tried with Chrome and Edge. Same result.

Seems like somethings broken to me, but I may be wrong.

Regards

Cray_T90

**Comment by noahc3** [comment]
Can you check the console (press F12 in your browser and go to the console tab) and tell me the last few lines?

**Comment by crayt90** [comment]
Active resource loading counts reached to a per-frame limit while the tab is in background. Network requests will be delayed until a previous loading finishes, or the tab is foregrounded. See <URL> for more details
www.googletagmanager.com/gtag/js?id=UA-124060019-1:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
blazor.webassembly.js:1 WASM: Initialized
blazor.webassembly.js:1 WASM: https://www.sdsetup.com/console?switch
blazor.webassembly.js:1 WASM: Mono: GC_MAJOR_SWEEP: major size: 2112K in use: 26330K
blazor.webassembly.js:1 WASM: Mono: GC_MAJOR: (LOS overflow) time 15.30ms, stw 15.30ms los size: 2048K in use: 140K
blazor.webassembly.js:1 WASM: Mono: GC_MINOR: (LOS overflow) time 0.40ms, stw 0.50ms promoted 0K major size: 2112K in use: 747K los size: 2048K in use: 140K
methods.js:76 Downloading https://glcdn.githack.com/noahc3/sdsetupfiles/raw/master/reinx/v1.7.1/sd/bootloader/payloads/ReiNX.bin
glcdn.githack.com/noahc3/sdsetupfiles/raw/master/reinx/v1.7.1/sd/bootloader/payloads/ReiNX.bin:1 Failed to load resource: net::ERR_SSL_PROTOCOL_ERROR
methods.js:132 File download failed, retrying...
methods.js:76 Downloading https://glcdn.githack.com/noahc3/sdsetupfiles/raw/master/reinx/v1.7.1/sd/bootloader/payloads/ReiNX.bin
glcdn.githack.com/noahc3/sdsetupfiles/raw/master/reinx/v1.7.1/sd/bootloader/payloads/ReiNX.bin:1 Failed to load resource: net::ERR_SSL_PROTOCOL_ERROR
methods.js:132 File download failed, retrying...
methods.js:76 Downloading https://glcdn.githack.com/noahc3/sdsetupfiles/raw/master/reinx/v1.7.1/sd/bootloader/payloads/ReiNX.bin
glcdn.githack.com/noahc3/sdsetupfiles/raw/master/reinx/v1.7.1/sd/bootloader/payloads/ReiNX.bin:1 Failed to load resource: net::ERR_SSL_PROTOCOL_ERROR
methods.js:132 File download failed, retrying...
methods.js:76 Downloading https://glcdn.githack.com/noahc3/sdsetupfiles/raw/master/reinx/v1.7.1/sd/bootloader/payloads/ReiNX.bin
glcdn.githack.com/noahc3/sdsetupfiles/raw/master/reinx/v1.7.1/sd/bootloader/payloads/ReiNX.bin:1 Failed to load resource: net::ERR_SSL_PROTOCOL_ERROR
methods.js:136 File download failed too many times, cancelling.
blazor.webassembly.js:1 WASM: File download failed, aborting...
methods.js:76 Downloading https://glcdn.githack.com/noahc3/sdsetupfiles/raw/master/reinx/v1.7.1/sd/bootloader/payloads/ReiNX.bin
glcdn.githack.com/noahc3/sdsetupfiles/raw/master/reinx/v1.7.1/sd/bootloader/payloads/ReiNX.bin:1 Failed to load resource: net::ERR_SSL_PROTOCOL_ERROR
methods.js:136 File download failed too many times, cancelling.
blazor.webassembly.js:1 WASM: File download failed, aborting...
blazor.webassembly.js:1 WASM: Mono: GC_MINOR: (Nursery full) time 11.40ms, stw 11.70ms promoted 777K major size: 2848K in use: 1779K los size: 4096K in use: 2817K
methods.js:76 Downloading https://glcdn.githack.com/noahc3/sdsetupfiles/raw/master/reinx/v1.7.1/sd/bootloader/payloads/ReiNX.bin
glcdn.githack.com/noahc3/sdsetupfiles/raw/master/reinx/v1.7.1/sd/bootloader/payloads/ReiNX.bin:1 Failed to load resource: net::ERR_SSL_PROTOCOL_ERROR
methods.js:136 File download failed too many times, cancelling.
blazor.webassembly.js:1 WASM: File download failed, aborting...
methods.js:76 Downloading https://glcdn.githack.com/noahc3/sdsetupfiles/raw/master/reinx/v1.7.1/sd/bootloader/payloads/ReiNX.bin
glcdn.githack.com/noahc3/sdsetupfiles/raw/master/reinx/v1.7.1/sd/bootloader/payloads/ReiNX.bin:1 Failed to load resource: net::ERR_SSL_PROTOCOL_ERROR
methods.js:136 File download failed too many times, cancelling.
blazor.webassembly.js:1 WASM: File download failed, aborting...
methods.js:76 Downloading https://glcdn.githack.com/noahc3/sdsetupfiles/raw/master/reinx/v1.7.1/sd/bootloader/payloads/ReiNX.bin
glcdn.githack.com/noahc3/sdsetupfiles/raw/master/reinx/v1.7.1/sd/bootloader/payloads/ReiNX.bin:1 Failed to load resource: net::ERR_SSL_PROTOCOL_ERROR
methods.js:136 File download failed too many times, cancelling.
blazor.webassembly.js:1 WASM: File download failed, aborting...
blazor.webassembly.js:1 WASM: Mono: GC_MINOR: (Nursery full) time 4.10ms, stw 4.10ms promoted 209K major size: 3616K in use: 2642K los size: 7168K in use: 5837K

**Comment by crayt90** [comment]
Just FYI 

Tried on my Android phone.
Works right away.

**Comment by noahc3** [comment]
Can you try going to glcdn.githack.com/noahc3/sdsetupfiles/raw/master/reinx/v1.7.1/sd/bootloader/payloads/ReiNX.bin and see what happens? It should download ReiNX.bin if it works.

**Comment by crayt90** [comment]
when I try with "https" I get
"ERR_SSL_PROTOCOL_ERROR"

when I try by "http" my AntiVirus (F-Secure Internet Security) kicks in with a malicious website warning.

**Comment by noahc3** [comment]
That's the issue then, the anti-virus is interfering with the download. Apparently CDNs like githack and rawgit have been used to distribute malware since the files don't have any verification and are cached forever. The AV is probably blanket blocking the githack domain.

In the near-ish future, I'll likely be moving file hosting to my own dedicated server so problems like this don't occur. In the meantime, you can disable your anti-virus to bypass this.

**Comment by crayt90** [comment]
understood

great support and response frequency by the way ;)
