### ISSUE TITLE
HBMenu key combo default value not recognized in CFW Settings

### ISSUE THREAD

**Issue by snifer1981** [noahc3/SDSetup#31]
I'm using Kosmos v11.0.
In CFW Settings, the HBMenu key combo default value is not recognized (there's a question mark). If I save settings (not changing that question mark to another value), there's no way to access HBMenu anymore.

Also, B button is shown as "back", but it doesn't work. I'm not sure how to exit CFW Settings without saving. + button does nothing either.

**Comment by noahc3** [comment]
Could you open an issue for this on the [cfw settings repo](https://github.com/AtlasNX/CFW-Settings/issues)?

**Comment by snifer1981** [comment]
Done. I wasn't sure if it's SDSetup specific or not.
