### ISSUE TITLE
Doesn't work in OSX Safari

### ISSUE THREAD

**Issue by noahc3** [noahc3/SDSetup#32]
Finally verified with a VM.

**Comment by noahc3** [comment]
Works fine in Technology Preview, I guess we wait for that to hit stable.

**Comment by wababc** [comment]
tested on real Mac OS Mojave 10.14.3 on Safari Version 12.0.3 (14606.4.5).
if more test is needed please ask.

**Comment by noahc3** [comment]
Ah, then I guess this is fixed. Thanks!
