### ISSUE TITLE
Atmosphere bug

### ISSUE THREAD

**Issue by jbmagination** [noahc3/SDSetup#37]
After running Atmosphere with the files provided by SDSetup, I went into RCM to find that Atmosphere would not load. I had to manually get Atmosphere 0.8.2, add all the files to my SD card, and get the payload.

I recommend that you quickly resolve this issue for future SDSetup users.

Thank you!

**Comment by noahc3** [comment]
I can't reproduce this, can you send me the log from the browser console?

**Comment by jbmagination** [comment]
I don't remember exactly what I selected, but this should be close 

---

CFW: Atmosphere

---

Customizations: All except `sys-netcheat`

---

Homebrew:

General: All
Utilities: All except `JK's Save Manager` and `EdiZon`
Games: All
Emulators: `RetroArch`

Customize RetroArch: All

---

Extras:

Payload: `fusee-primary`
Windows Tools: `4NXCI`, `hactool`, `nspbuild`, `Switch Backup Manager`

---

If that doesn't work, here is my SD Setup ZIP file:
https://github.com/jbmagination/sdsetup/releases

**Comment by noahc3** [comment]
Were you trying to launch with fusee-primary or hekate?

**Comment by jbmagination** [comment]
I was attempting to launch with fusee-primary

**Comment by noahc3** [comment]
Alright I see the issue, I forgot to update fusee-secondary. Will fix.

**Comment by noahc3** [comment]
Should be fixed now.
