### ISSUE TITLE
Download doesn't package atmosphere correctly

### ISSUE THREAD

**Issue by idcipher106** [noahc3/SDSetup#38]
When you download a zip file, the atmosphere folder doesn't even contain fusee-secondary.bin.  Instead fusee-secondary.bin is in the root folder, but it needs to be moved into the atmosphere folder.  Nothing works without the files in the right places.

**Comment by 16BitWonder** [comment]
Will also chime in that BCT.ini's default location is also now in the atmosphere\ directory.
Might want to relocate it there.

Both of these changes can be found in this commit:
https://github.com/Atmosphere-NX/Atmosphere/commit/49ba3a86e2f574234030130c9c3564f4c5d57b76

**Comment by noahc3** [comment]
I'm going to move the new SDSetup that uses the new backend to production later today which will fix these issues.

**Comment by noahc3** [comment]
Should be fixed now.

Note Kosmos uses Atmosphere 0.8.1, so fusee-secondary.bin is still in the root folder.
