### ISSUE TITLE
Credits page too wide for mobile 

### ISSUE THREAD

**Issue by pbsds** [noahc3/SDSetup#4]
Neat page. The credits page could you se some css media queries to work on mobile though. 

Edit:
The URLs might be too long, causing the page to expand. Try using css ellipsis or insert some breakpoints. You could also change the link labels to something shorter instead

**Comment by noahc3** [comment]
The problem is that semantic ui is a little bit broken in this blazor setup and for some reason is showing text on a single line even though that class isn't specified. I'll look into fixing this.
