### ISSUE TITLE
Pre-configured build is missing for ReiNX

### ISSUE THREAD

**Issue by shyim** [noahc3/SDSetup#43]
The preconfigured build are removed for ReiNX. Will it come back?

**Comment by noahc3** [comment]
What do you mean?

**Comment by shyim** [comment]
https://i.imgur.com/6WcRycw.png

The third selection for ReiNX is missing :)

**Comment by noahc3** [comment]
There never was a bundle for reinx, there used to be an 'Everything' bundle which selected all of the packages, but I removed it to encourage less bandwidth use on my server.

Depending on how much data gets used this month I might bring back the everything bundle but no promises.

**Comment by noahc3** [comment]
Little update, I've added a ReiNX bundle which has all of the packages you would get by following reinx.guide.
