### ISSUE TITLE
Pack payload for SX dongle

### ISSUE THREAD

**Issue by jayme-github** [noahc3/SDSetup#45]
A nice addition would be to allow packing of payload on SX custom format (https://gist.github.com/CTCaer/13c02c05daec9e674ba00ce5ac35f5be)

**Comment by noahc3** [comment]
Won't add, it's complicated to implement and not in the spirit of SDSetup to support FOSS applications only. I think most people can probably just have a hekate bin in boot.dat format to chainload other payloads from.
