### ISSUE TITLE
Download Failed, not starting making the zip file.

### ISSUE THREAD

**Issue by Conan179** [noahc3/SDSetup#47]
Hi!
I cand making a packeg for my sd card.
I become only the error Massage:
"Download Failed
It looks like the backend server may have gone down while you were here. Try again later"

**Comment by Matt1412** [comment]
same thing happen to me.
Happen with FireFox and Chrome.

**Comment by noahc3** [comment]
Can one of you send me a screenshot of the console and network tab in dev tools when this happens?

**Comment by Matt1412** [comment]
> Can one of you have dev tools open (F12) before you try a download and then send me a screenshot of the console and network tabs afterwards?

![screenshot from 2018-12-22 08-04-40](https://user-images.githubusercontent.com/15963945/50368122-749fcc00-05c0-11e9-863e-f8e29056be46.png)
![screenshot from 2018-12-22 08-05-32](https://user-images.githubusercontent.com/15963945/50368124-75386280-05c0-11e9-8eb8-9102b68394c6.png)

**Comment by noahc3** [comment]
Thanks, I can reproduce this now With a large number of items the server can take >60 seconds to package it and as such the browser will timeout. I'll see what I can do to fix this.

**Comment by noahc3** [comment]
Actually thankfully it was nginx, fixed!

**Comment by Matt1412** [comment]
Tested again and i am able to download if i select all options.
Thanks.
