### ISSUE TITLE
Two different versions of ReiNX payload included

### ISSUE THREAD

**Issue by szymonpk** [noahc3/SDSetup#48]
In `pc/payloads` I have different ReiNX version than in `sd/bootloader/payloads`, the first one does not support 6.2

See [my custom SDSetup link](https://www.sdsetup.com/console?switch#reinx;reinx_toolkit;hbmenu;pplay;tinfoil;zerotwoxci;nxshell;lockpick;retroarch;khedgb;vbanextswitch;psnes;pfba;scummvm;retroarch_beetlevb;retroarch_fceumm;retroarch_quicknes;retroarch_nestopia;retroarch_snes9x;retroarch_snes9x2010;retroarch_pcsxra;retroarch_picod;retroarch_gengxp;retroarch_yabause;retroarch_gearsystem;retroarch_stella;retroarch_prosys;retroarch_4do;retroarch_o2em;retroarch_vecx;retroarch_freeintv;retroarch_nxe;retroarch_gambatte;retroarch_mgba;retroarch_vbanext;retroarch_pokemini;retroarch_tgbdual;retroarch_gearboy;retroarch_handy;retroarch_wswan;retroarch_ngp;retroarch_mameplus;retroarch_fba;retroarch_mame2000;retroarch_mame;retroarch_pcefast;retroarch_sgrafx;retroarch_dosbox;retroarch_fmsx;retroarch_vice;retroarch_tyrquake;retroarch_mrboom;retroarch_cannonball;retroarch_prboom;retroarch_reminiscence;retroarch_xrick;reinx_payload;hekate;briccmii;gptrestore;biskeydump;fusee-launcher;).

**Comment by noahc3** [comment]
Fixed. I've also updated the payload for TegraRCMGui even though it hasn't been updated officially.

Everything is now ReiNX v2.0.
