### ISSUE TITLE
Server is down

### ISSUE THREAD

**Issue by SheikFlorian** [noahc3/SDSetup#52]
![image](https://user-images.githubusercontent.com/47093210/51848483-d3b1d880-2304-11e9-9025-9b7e649190fa.png)

And since the footnote says to report here, here I'm.

**Comment by Conan179** [comment]
https://github.com/noahc3/SDSetup/issues/51

**Comment by SheikFlorian** [comment]
> #51

The way noach3 said on the last post of the thread I tought that the issue was fixed for a short period of time and than happened again

**Comment by noahc3** [comment]
Going to try moving the server to a different location because that data center is being a real PoS.

**Comment by noahc3** [comment]
Server is back, another error on the hosts end. I'll get some redundancy set up as soon as possible.
