### ISSUE TITLE
Corrupt zip

### ISSUE THREAD

**Issue by trevor7oaks** [noahc3/SDSetup#65]
Tried a number of times to dl Kosmos default bundle zip but each time the zip won’t extract as it is currupt

**Comment by noahc3** [comment]
How big is the zip being downloaded?

**Comment by trevor7oaks** [comment]
Hi

A couple of times 28mb and 33mb. Once was 178mb, the first 2 I was using chrome on a Mac. The largest was using silk browser on my android tablet. This one extracted the sd folder (but I’m not sure if fully) and crashed whilst extracting mame (retroarch).

Do you have a list of the sd content so I can check what did extract?

Trevor 

07375 390365

**Comment by noahc3** [comment]
This might be a result of the server not being *fully* back yet, packets might be getting dropped.

I don't have a list of what files you should have since that would depend on the packages you picked.

I'll let you know when everything is supposed to be fully back so you can check again if things are being extracted correctly.

**Comment by trevor7oaks** [comment]
Default bundle plus retroarch (4do).  Thanks for letting me know what’s going on. Look forward to hearing from you further.

**Comment by trevor7oaks** [comment]
Hi tried last night with the standard Kosmos bundle no extras and the zip was still corrupt. Any update?

**Comment by noahc3** [comment]
@trevor7oaks Can you try one more time? Apparently the host should be (mostly) back to normal now.

If it's still corrupt, can you give me

- The link SDSetup generates after you press download for sharing
- Your browser and version
- Your OS and version

**Comment by trevor7oaks** [comment]
Still did not work, all that downloaded is sd/sept/sept-secondary.bin

I use Mac OSX 10.10.5
Chrome browser
No link, it just starts downloading

Trevor

**Comment by noahc3** [comment]
Should create a link at the top.

![](https://puu.sh/CYKxx/18ced37434.png)
