### ISSUE TITLE
Update to Atmo 0.8.5?

### ISSUE THREAD

**Issue by LilaQ** [noahc3/SDSetup#68]
Hi there,

I was under the impression that it was an automated process, but it apparently is still at 0.8.4, so any timeframe when Atmo will be updated to 0.8.5? Just want to know, if it's worth the wait, as I have to prep a few Switches in the next days.

Thanks in advance for all the effort!

**Comment by noahc3** [comment]
As soon as Hekate updates. 

After this next version of Hekate, Atmosphere *should* be updated when official releases are made, without having to wait for Kosmos updates. The only exception should be when there are changes necessary to support newer firmwares if Nintendo pulls any more tricks.

**Comment by LilaQ** [comment]
Hekate is at 4.9.1 now, fyi

**Comment by bored-person** [comment]
@LilaQ make a commit then with the updated hekate, you really dont need to ask tbh

**Comment by LilaQ** [comment]
...yeah, right

**Comment by noahc3** [comment]
@bored-person what? 

I'll get it updated later today.

**Comment by noahc3** [comment]
Done
