### ISSUE TITLE
sdfiles seems only partially updated for 11.11.1

### ISSUE THREAD

**Issue by uberyoji** [noahc3/SDSetup#70]
I might be wrong but it seems like only the main kosmos package was updated on sdfiles.
For example:
- sigpatches are marked v11.10.0, should be v11,11,1
https://github.com/AtlasNX/Kosmos/releases/download/v11.11.1/Additional.SigPatches.espatches.zip
- hekate is still v4.8, should be v4.9.1
https://github.com/CTCaer/hekate/releases/download/v4.9.1_/hekate_ctcaer_4.9.1.zip
- in payload, fusee-primary is listed as v0.8.4 should be v0.8.5
https://github.com/Atmosphere-NX/Atmosphere/releases/download/0.8.5/fusee-primary.bin

**Comment by noahc3** [comment]
Fixed, thanks for pointing out each issue.
