### ISSUE TITLE
Zip doesn't download

### ISSUE THREAD

**Issue by Pokapa** [noahc3/SDSetup#71]
When I try to download a package the only file I get is a txt file with the word "Expired" in it, I already close my antivirus and the problem persists, any help?
[0acd601b10644044a2546749a03832d7.txt](https://github.com/noahc3/SDSetup/files/2955620/0acd601b10644044a2546749a03832d7.txt) <--- This is what I get

**Comment by noahc3** [comment]
A couple people are getting this, I'm going to rework the expiry system to try and fix this. Hang tight.

**Comment by Pokapa** [comment]
Thanks, Much appreciate! :)

**Comment by viktortrass** [comment]
I cannot download the zip, stuck at building your zip

**Comment by ReanimationXP** [comment]
Same, cannot download. Keeps stalling for a long time then saying the backend server went down.

**Comment by feraligatr** [comment]
> Same, cannot download. Keeps stalling for a long time then saying the backend server went down.
Same for me.
#85 still happens for me.

**Comment by noahc3** [comment]
Can someone who was experiencing this check if it still happens? The code has changed a bit so I want to make sure the bug is still present.

**Comment by Bennyvon88** [comment]
Hi.
I can't download zipfile: it downloads a invalid file of less of 10ko. I tried many times and it's always same thing.
Here is one of those downloads....
[19)(1).zip](https://github.com/noahc3/SDSetup/files/3485656/19.1.zip)

**Comment by noahc3** [comment]
It's techically my fault, my file expiry system breaks with pausing and download managers. I have an idea to fix this but I won't be able to work on this until after the 16th.

**Comment by noahc3** [comment]
Moved the issue here: https://github.com/noahc3/SDSetup/issues/168

**Comment by noahc3** [comment]
These issues should be fixed by 851c753
