### ISSUE TITLE
Site Down 3/16/2019

### ISSUE THREAD

**Issue by colton-lad** [noahc3/SDSetup#75]
![sdsetup_down](https://user-images.githubusercontent.com/14880562/54479551-d81a4e00-47eb-11e9-9f25-ef57207196b5.png)

It told me to...

**Comment by noahc3** [comment]
welp this at least confirms guide redundancy is working 😓 

gimme a few minutes

**Comment by amartpache** [comment]
not to be bothersome by re-iterating this but yeah it was down for me and said to report it on here

**Comment by noahc3** [comment]
Site's back

**Comment by amartpache** [comment]
thank you!
