### ISSUE TITLE
Consider adding nxmtp as optional download

### ISSUE THREAD

**Issue by Zireael** [noahc3/SDSetup#77]
nxmtp
A (good enough) MTP responder for the Switch.
https://github.com/liuervehc/nxmtp

Lets you mount Switch partitions as USB drive partitions on PC (I use it on Windows).
Works well enough for me and is great help. Only thing missing that I can see is it doesn't overwrite files at destination if the same file name already exists. You need to rename/delete old file first.
Alas, very useful program.

**Comment by noahc3** [comment]
Want to avoid putting closed source software on SDSetup as much as possible. @friedkeenan is working on an open source MTP responder and hopes to have it out soon-ish, so I'd like to wait for that.

**Comment by noahc3** [comment]
Added mtp-server-nx.
