### ISSUE TITLE
ReiNX and Toolkit need updating

### ISSUE THREAD

**Issue by Endar-Marit** [noahc3/SDSetup#79]
Both ReiNX and the toolkit hosted on sd setup are out of date. Please update reinx from their guide
[Here](https://reinx.guide/downloads/ReiNX_2.1.zip), and the updated toolkit from [here](https://github.com/Reisyukaku/ReiNXToolkit/releases/download/v1.3/ReiNXToolkit.zip) or [here](https://reinx.guide/downloads/ReiNXToolkit.nro). Thankyou :)

**Comment by tumGER** [comment]
Noahc will update it, thanks for letting us know ;)

**Comment by noahc3** [comment]
Done
