### ISSUE TITLE
Client times out after 60 seconds, preventing download of larger packages

### ISSUE THREAD

**Issue by feraligatr** [noahc3/SDSetup#85]
I selected everything, but:
"Download Failed
It looks like the backend server may have gone down while you were here. Try again later."

BTW, could you provide an "Everything package" on mediafire/google drive/dropbox/mega to save server load?

**Comment by noahc3** [comment]
Can you tell me your browser and OS? Additionally, can you open the console in your browser (press F12), reload the page and try to download another package and send me any messages logged into the console?

**Comment by noahc3** [comment]
Nvm, I'm able to reproduce this. Browser is timing out the request just before the ZIP finishes packaging.

**Comment by ReanimationXP** [comment]
Same issue, showed after a minute or two. Chrome Win10.
![image](https://user-images.githubusercontent.com/2142085/56973429-afdb7a00-6b21-11e9-883a-aa65bdfb7348.png)

**Comment by RiPPERD** [comment]
i have same issue - Win10 X64 - Firefox latest version - only has the issue when i enable retroarch.
if i untick retroarch it works fine with everything else ticked for both atmosphere and renix in same package

**Comment by RiPPERD** [comment]
this issue is still happening and only seems to happen when retroarch is ticked
