### ISSUE TITLE
Atmosphere package is outdated

### ISSUE THREAD

**Issue by PeteSeta** [noahc3/SDSetup#87]
Current ver. is 0.8.7. SDSetup shows 0.8.6

**Comment by TehPsychedelic** [comment]
Where does it show 0.8.6 for you. I reckon it was updated to 0.8.7 when it dropped and that was a few days ago.

**Comment by PeteSeta** [comment]
It's 0.8.7 now. Yesterday where it says "Atmosphere (Kosmos)" under the CFW section the ver. no. was v12.0.1/v0.8.6.

**Comment by noahc3** [comment]
12.0.1 was always 0.8.7 :P
