### ISSUE TITLE
Server throws randomly and inconsistently on latest commits

### ISSUE THREAD

**Issue by RealSpyKitty** [noahc3/SDSetup#88]
Its building the zip file but never finishes. (multiple files ~5)

===================================================================

Known:
- Only happens on newer commits w/ download stats
- Throws [somewhere in here](https://github.com/noahc3/SDSetup/blob/master/SDSetupBackend/Controllers/v1.cs#L56)
- Packages selected does not seem to matter
- Likely not a problem caused by the client

**Comment by ubenmackin** [comment]
Same thing is happening to me. Just tried twice, and it just spins.

**Comment by noahc3** [comment]
Can someone open the console window in your browser (press F12), try downloading again and send me any errors that pop up?

**Comment by ubenmackin** [comment]
@noahc3 Just went to do this, and the download started for me. So maybe just a temp hiccup.

**Comment by 50PercentLuck** [comment]
![Capture](https://user-images.githubusercontent.com/49773987/56404665-ee298d00-6235-11e9-98b0-55979da614d6.PNG)
Here's a pic of what I think you requested noahc3. Not very tech savvy, but seemed like easy instructions.

**Comment by tmo27** [comment]
Having the exact same error codes as @50percentluck. Turned off anything that could be blocking it.

**Comment by noahc3** [comment]
I really need to stop logging useless error messages :P

Can you guys do the same thing again but at https://testing.sdsetup.com/ instead

**Comment by tmo27** [comment]
It downloaded perfectly fine from that link with 0 errors.

**Comment by noahc3** [comment]
Can you test again on the original link?

**Comment by tmo27** [comment]
Original link working fine now too. 0 errors as well, I wish I was making this up.

**Comment by noahc3** [comment]
@50PercentLuck Can you try

**Comment by 50PercentLuck** [comment]
it works for me now

**Comment by C1BERUS** [comment]
I also got the same issue... trying on sdsetup and test.sdsetup 

![111111](https://user-images.githubusercontent.com/30430080/56409238-5ada7100-62a2-11e9-82e1-524d4b616359.png)

**Comment by swagathaur** [comment]
![image](https://user-images.githubusercontent.com/16999501/56409320-e3b1d680-62bb-11e9-8210-7e724ce6ab17.png)
Same issue here, hope this helps at all.

**Comment by noahc3** [comment]
I *think* this is an issue with the download stats tracking, but I'll need to do more testing to find out. In the meantime I've reverted the server software to an older version without the new stuff.

**Comment by C1BERUS** [comment]
> I also got the same issue... trying on sdsetup and test.sdsetup
> 
> ![111111](https://user-images.githubusercontent.com/30430080/56409238-5ada7100-62a2-11e9-82e1-524d4b616359.png)

It's working right now, thanks @noahc3  👍

**Comment by noahc3** [comment]
This is **probably fixed** for now but I'll keep the issue open until I figure out the issue in the newer commits.

**Comment by fourminute** [comment]
I've never had an issue with SDSetup and I've used it for all of my Switch's probably at least a few dozen times.

**Comment by noahc3** [comment]
This is "fixed" as I have removed the current download stats implementation altogether while i work on a replacement.
