### ISSUE TITLE
SSL Cert Expired

### ISSUE THREAD

**Issue by RiPPERD** [noahc3/SDSetup#89]
your website cannot be accessed due to invalid cert/expired cert (ran out today 30/04/2019)

can you please update

**Comment by 2g4y1** [comment]
take a look here for the future =D
it`s a nice reminder
https://certificate.tools/expiry-notification

**Comment by noahc3** [comment]
Netlify usually renews the cert automatically, apparently there was an error and their notification service failed to send an email.

**Comment by RiPPERD** [comment]
if you use firefox developer edition it allows you to bypass this cert problem... for those that it might help

**Comment by noahc3** [comment]
I've temporarily redirected the sdsetup domain to the default netlify domain until they fix the problem.

**Comment by RiPPERD** [comment]
yes i can confirm this is now working

**Comment by noahc3** [comment]
Fixed
