### ISSUE TITLE
Old sept and fusee-primary packaged

### ISSUE THREAD

**Issue by dreambottle** [noahc3/SDSetup#90]
Hey, I noticed that sdsetup includes the wrong `/sept/payload.bin` in the package.

This causes a crash when booting Atmosphere 0.8.9 with fusee-primary payload (hekate, strangely, works fine)

The crash happens after "Nintendo Switch" logo and the error says "Atmosphere version mismatch detected" in Title: 0100000000000037.

Also, the provided fusee-primary is old, it needs to be updated for Atmosphere 0.8.9

**Comment by noahc3** [comment]
The crash is because of the fusee primary being outdated, I'll fix it.

The payload in the sept folder is hekate.

**Comment by dreambottle** [comment]
What do you mean by "is hekate"? It's a 5mb binary, distributed with atmosphere.

**Comment by friedkeenan** [comment]
`/sept/payload.bin` is the payload sept launches. `/sept/sept-secondary.enc` is the encrypted sept-secondary payload

**Comment by dreambottle** [comment]
I just noticed that size and hashes for `/sept/payload.bin` differ from what's distributed with Atmosphere 0.8.9.

I am not familiar with what `sept-secondary` does. Does it matter in this case?

**Comment by luke187** [comment]
Its still not updated just checking to see if there was a timeframe on when it wold be updated?

**Comment by noahc3** [comment]
Done! Sorry for the delay, I was away at a competition for a week and didn't have time to get this updated sooner.
