### ISSUE TITLE
Fluffy updated to v2.8

### ISSUE THREAD

**Issue by fourminute** [noahc3/SDSetup#93]
This release adds Goldleaf v0.5 support. A really important functionality as the current version only supports v0.4.

**Comment by fourminute** [comment]
Also keep an eye out for Goldleaf v0.6 release, once that is released I will immediately release the next version of Fluffy for compatibility reasons. 

I would have released the next version already(it's ready) but there's no point as Goldleaf v0.6 hasn't released yet.

**Comment by noahc3** [comment]
Done! Sorry for the delay, I was away at a competition for a week and didn't have time to get this updated sooner.
