### ISSUE TITLE
Incomplete Zip Download...

### ISSUE THREAD

**Issue by CypherAce** [noahc3/SDSetup#96]
I'm running into an issue after I make all my selections and hit the "Download Your Zip". The download seems to process but the zip file is incomplete and will have various sizes. When I say incomplete, I mean that 7z throws an error that data cut off unexpectedly and its missing components of my selection.

**Comment by noahc3** [comment]
This was just fixed, can you refresh and try again?

**Comment by CypherAce** [comment]
It seems to still be happening, at least for me. I went back to the base site (sdsetup.com), made all my selections again and tried to download it but it was the same issue.

**Comment by noahc3** [comment]
Alright I think I've actually fixed the issue this time, try again please.

**Comment by CypherAce** [comment]
Yes, it seems you did. Thanks for the quick fix!
